version: '3.7'

services:
  # streamlit:
  #   build:
  #     context: ./streamlit_app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8501:8501"  # Match the port to the one Streamlit runs on
  #   depends_on:
  #     - fastapi
  #   restart: unless-stopped
  #   networks:
  #     - sign


  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn app_fastapi:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    image: fastapi
    mem_limit: 2g
    networks:
      - sign

networks:
  sign:
    driver: bridge